# Spring Data Source ?? - Mysql db ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: park
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true